apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: azurite
  name: azurite
spec:
  replicas: 1
  progressDeadlineSeconds: 60
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: azurite
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: azurite
    spec:
      containers:
        - image: mcr.microsoft.com/azure-storage/azurite
          imagePullPolicy: IfNotPresent
          name: azurite
          ports:
            - containerPort: 15672
              name: http-management
              protocol: TCP
            - containerPort: 5672
              name: amqp
              protocol: TCP
          resources:
            limits:
              cpu: 300m
              memory: 400Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
