apiVersion: v1
kind: Service
metadata:
  labels:
    app: azurite
  name: azurite
spec:
  ports:
    - name: blob
      port: 10000
      protocol: TCP
      targetPort: 10000
    - name: queue
      port: 10001
      protocol: TCP
      targetPort: 10001
  selector:
    app: azurite
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}