resources:
  - ../production
  - infrastructure
  - tables
patches:
  - target:
      group: delta-operator.rs
      version: v1alpha1
      kind: DeltaTable
    patch: |
      apiVersion: apiextensions.k8s.io/v1
      kind: CustomResourceDefinition
      metadata:
        name: ignored
        annotations:
          tilt.dev/down-policy: keep
  - patch: |
      apiVersion: apiextensions.k8s.io/v1
      kind: CustomResourceDefinition
      metadata:
        name: deltatables.delta-operator.rs
        annotations:
          tilt.dev/down-policy: keep
    target:
      group: apiextensions.k8s.io
      version: v1
      kind: CustomResourceDefinition
      name: deltatables.delta-operator.rs
  - target:
      kind: Deployment
      name: delta-operator
      version: v1
      group: apps
    patch: |
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: delta-operator
        namespace: delta-operator-system
      spec:
        template:
          spec:
            containers:
              - name: controller
                args:
                  - --listen-address
                  - 0.0.0.0:8080
                  - --image
                  - $(SERVICE_CONTAINER_IMAGE)
                  - --worker-service-account
                  - delta-operator
                image: docker-delta-operator
                env:
                  - name: SERVICE_CONTAINER_IMAGE
                    value: docker-delta-operator-worker
                  - name: AZURITE_BLOB_STORAGE_URL
                    value: "http://azurite:10000"