apiVersion: v1
kind: Service
metadata:
  labels:
    app: localstack
  name: localstack
spec:
  ports:
    - name: http
      port: 4566
      protocol: TCP
      targetPort: 4566
  selector:
    app: localstack
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}