apiVersion: v1
kind: Service
metadata:
  name: delta-operator
  namespace: delta-operator-system
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: delta-operator
